# Generated by Django 3.2.4 on 2021-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('1', 'Manager'), ('2', 'Senior'), ('3', 'Middle'), ('4', 'Junior'), ('5', 'Courier'), ('6', 'Customer')], default=6, max_length=100, verbose_name='Role'),
        ),
    ]
