# Generated by Django 3.2.4 on 2021-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210704_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Senior', 'Senior'), ('Middle', 'Middle'), ('Junior', 'Junior'), ('Courier', 'Courier'), ('Customer', 'Customer')], default=6, max_length=100, verbose_name='Role'),
        ),
    ]
