# Generated by Django 3.2.4 on 2021-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210726_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.TextField(blank=True, default='Name', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.TextField(blank=True, default='Familiya', null=True),
        ),
    ]
