# Generated by Django 3.2.4 on 2021-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210726_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='description',
            field=models.TextField(blank=True, default='00'),
        ),
    ]
