# Generated by Django 3.2.4 on 2021-07-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('1', 'За Перевозку'), ('2', 'За Товар'), ('3', 'За Перевод'), ('4', 'Возврат')], max_length=255, null=True, verbose_name='Service'),
        ),
    ]
