# Generated by Django 3.2.4 on 2021-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
