# Generated by Django 3.2.4 on 2021-07-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
