# Generated by Django 3.2.4 on 2021-06-28 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Moneys', '0001_initial'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerexpenseshistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='plan',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Services.plan'),
        ),
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_add_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerexpenses',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customerexpenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_add', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customeraccounthistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_add_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customeraccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
