# Generated by Django 3.2.4 on 2021-06-28 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Moneys', '0003_alter_customeraccount_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customeraccount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='staff',
            field=models.ForeignKey(default='Users.UserModel', on_delete=django.db.models.deletion.CASCADE, related_name='staff_add_one', to=settings.AUTH_USER_MODEL),
        ),
    ]
