# Generated by Django 3.2.4 on 2021-06-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0006_customeraccount_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraccount',
            old_name='us',
            new_name='currency',
        ),
    ]
