# Generated by Django 3.2.4 on 2021-06-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0007_rename_us_customeraccount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounthistory',
            name='currency',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
