# Generated by Django 3.2.4 on 2021-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0009_remove_customeraccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='rub',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='usd',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='rub',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='usd',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerexpenses',
            name='rub',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerexpenses',
            name='usd',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='rub',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='usd',
            field=models.FloatField(blank=True, default='00', max_length=255),
        ),
    ]
