# Generated by Django 3.2.4 on 2021-07-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0011_auto_20210703_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='currency',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
