# Generated by Django 3.2.4 on 2021-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0012_alter_customeraccounthistory_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='currency',
            field=models.CharField(blank=True, default='00', max_length=255),
        ),
    ]
