# Generated by Django 3.2.4 on 2021-07-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0013_alter_customeraccounthistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='currency',
            field=models.CharField(blank=True, default='00', max_length=255),
        ),
    ]
