# Generated by Django 3.2.4 on 2021-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0014_customerexpenseshistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='description',
            field=models.TextField(default='00'),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='description',
            field=models.TextField(default='00'),
        ),
        migrations.AddField(
            model_name='customerexpenses',
            name='description',
            field=models.TextField(default='00'),
        ),
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='description',
            field=models.TextField(default='00'),
        ),
    ]
