# Generated by Django 3.2.4 on 2021-07-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service'),
        ('Moneys', '0015_auto_20210704_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='service',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='service', to='Services.service'),
        ),
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='plan',
            field=models.ForeignKey(blank=True, default='3', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Services.plan'),
        ),
    ]
