# Generated by Django 3.2.4 on 2021-07-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_service_name'),
        ('Moneys', '0016_auto_20210704_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='Services.service'),
        ),
    ]
