# Generated by Django 3.2.4 on 2021-07-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0018_auto_20210704_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='description',
            field=models.TextField(blank=True, default='00'),
        ),
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='description',
            field=models.TextField(blank=True, default='00'),
        ),
        migrations.AlterField(
            model_name='customerexpenses',
            name='description',
            field=models.TextField(blank=True, default='00'),
        ),
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='description',
            field=models.TextField(blank=True, default='00'),
        ),
    ]
