# Generated by Django 3.2.4 on 2021-07-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_remove_service_price'),
        ('Moneys', '0019_auto_20210704_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounthistory',
            name='plan',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='plane', to='Services.plan'),
        ),
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='plan',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Services.plan'),
        ),
    ]
