# Generated by Django 3.2.4 on 2021-07-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0022_auto_20210704_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='customeraccounthistory_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accounthistory_id', to='Moneys.customeraccounthistory'),
        ),
    ]
