# Generated by Django 3.2.4 on 2021-07-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0023_alter_customerexpenseshistory_customeraccounthistory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerexpenseshistory',
            old_name='customeraccounthistory_id',
            new_name='customeraccounthistory',
        ),
    ]
