# Generated by Django 3.2.4 on 2021-07-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moneys', '0024_rename_customeraccounthistory_id_customerexpenseshistory_customeraccounthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='customeraccounthistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounthistory_id', to='Moneys.customeraccounthistory'),
        ),
    ]
